{
  "id": "BIT-lua-2021-44647",
  "details": "Lua v5.4.3 and above are affected by SEGV by type confusion in funcnamefromcode function in ldebug.c which can cause a local denial of service.",
  "aliases": [
    "CVE-2021-44647"
  ],
  "modified": "2024-03-06T11:25:28.861Z",
  "published": "2024-03-06T10:56:13.475Z",
  "database_specific": {
    "cpes": [
      "cpe:2.3:a:lua:lua:5.4.3:*:*:*:*:*:*:*"
    ],
    "severity": "Medium"
  },
  "references": [
    {
      "type": "WEB",
      "url": "http://lua-users.org/lists/lua-l/2021-11/msg00195.html"
    },
    {
      "type": "WEB",
      "url": "http://lua-users.org/lists/lua-l/2021-11/msg00204.html"
    },
    {
      "type": "WEB",
      "url": "https://access.redhat.com/security/cve/cve-2021-44647"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P3EMGAQ5Y6GXJLY4K5DUOOEQT4MZ4J4F/"
    },
    {
      "type": "WEB",
      "url": "https://security.gentoo.org/glsa/202305-23"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "lua",
        "ecosystem": "Bitnami",
        "purl": "pkg:bitnami/lua"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "5.4.3"
            },
            {
              "last_affected": "5.4.3"
            }
          ]
        }
      ],
      "database_specific": {
        "source": "https://github.com/bitnami/vulndb/tree/main/data/lua/BIT-lua-2021-44647.json"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
        }
      ]
    }
  ],
  "schema_version": "1.6.0"
}