{
  "id": "BIT-django-2024-41990",
  "details": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. The urlize() and urlizetrunc() template filters are subject to a potential denial-of-service attack via very large inputs with a specific sequence of characters.",
  "aliases": [
    "CVE-2024-41990",
    "GHSA-795c-9xpc-xw6g",
    "PYSEC-2024-68"
  ],
  "modified": "2024-08-08T08:11:46.336271Z",
  "published": "2024-08-08T07:17:28.897Z",
  "database_specific": {
    "cpes": [
      "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*"
    ],
    "severity": "High"
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://docs.djangoproject.com/en/dev/releases/security/"
    },
    {
      "type": "WEB",
      "url": "https://groups.google.com/forum/#%21forum/django-announce"
    },
    {
      "type": "WEB",
      "url": "https://www.djangoproject.com/weblog/2024/aug/06/security-releases/"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "django",
        "ecosystem": "Bitnami",
        "purl": "pkg:bitnami/django"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "4.2.0"
            },
            {
              "fixed": "4.2.15"
            },
            {
              "introduced": "5.0.0"
            },
            {
              "fixed": "5.0.8"
            }
          ]
        }
      ],
      "database_specific": {
        "source": "https://github.com/bitnami/vulndb/tree/main/data/django/BIT-django-2024-41990.json"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
        }
      ]
    }
  ],
  "schema_version": "1.6.0"
}