{
  "id": "BIT-moodle-2021-3943",
  "details": "A flaw was found in Moodle in versions 3.11 to 3.11.3, 3.10 to 3.10.7, 3.9 to 3.9.10 and earlier unsupported versions. A remote code execution risk when restoring backup files was identified.",
  "aliases": [
    "CVE-2021-3943",
    "GHSA-8jhp-2gcr-qw96"
  ],
  "modified": "2025-01-17T15:26:01.971Z",
  "published": "2024-03-06T11:07:54.805Z",
  "database_specific": {
    "cpes": [
      "cpe:2.3:a:moodle:moodle:*:*:*:*:*:*:*:*"
    ],
    "severity": "Critical"
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2021963"
    },
    {
      "type": "WEB",
      "url": "https://moodle.org/mod/forum/discuss.php?d=429095"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "moodle",
        "ecosystem": "Bitnami",
        "purl": "pkg:bitnami/moodle"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "3.9.0"
            },
            {
              "last_affected": "3.9.10"
            },
            {
              "introduced": "3.10.0"
            },
            {
              "last_affected": "3.10.7"
            },
            {
              "introduced": "3.11.0"
            },
            {
              "last_affected": "3.11.3"
            }
          ]
        }
      ],
      "database_specific": {
        "source": "https://github.com/bitnami/vulndb/tree/main/data/moodle/BIT-moodle-2021-3943.json"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
        }
      ]
    }
  ],
  "schema_version": "1.6.0"
}